owner: unktower
repo: upptime
user-agent: unktower_upptime

# Sites
sites:
  - name: Website
    url: http://unktower.com
  - name: API
    url: $SECRET_URL_API

# Users to assign downtime issues
assignees: 
  - clazstudio
  - Unkntower

# Time intervals
workflowSchedule:
  uptime: "*/10 * * * *"

status-website:
  cname: status.unktower.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**UNKNOWNtower** uptime monitor and status page."
  introMessage: "Powered by [Upptime](https://github.com/koj-co/upptime)."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: http://unktower.com
    - title: Steam Group
      href: https://steamcommunity.com/gid/32362920

# https://upptime.js.org/docs/configuration
